### ISSUE TITLE
Can't Find App in Store and Broken Readme Link

### ISSUE THREAD

**Issue by decal** [Fortyseven/ToneDef#16]
Is ToneDef still in the Google Play store?  I have it installed on my phone, but I couldn't find it via search..
Also, the hyperlink in the repository's README markdown is a 404.  What's going on?  I love this app and need to cuddle with it.. 💟 ❓

**Comment by Fortyseven** [comment]
ToneDef is an awful two-timer who's had a rocky time with it's relationship with the Play store, so it's been seeing [F-Droid on the side](https://f-droid.org/en/packages/com.bytestemplar.tonedef/) on the side.

Seriously though, a while back Google delisted ToneDef because I didn't have a privacy policy in place and it accesses a user's contacts. Part of the new privacy requirements.

It's been a while and Android Studio is a real jerkwad, so I've been dragging my heels -- it LOOKED like I had to provide a link inside the app. 

But just now I took a look inside the console, and it let me "resubmit the app" once I dropped in a privacy policy page from my website.

So. It may be back sooner than I'd thought. Or it's available immediately though F-Droid. 

I also have an HTML5 version (it's not the one on Github; that's a much older proof of concept) that works great inside Chrome on mobile. I haven't touched that in a while, though. It was coming along nicely for a while there. Looked almost identical to the Android version, even. :P

Anyway! If you still have issues getting it, let me know. I **should** leave an APK here in the releases just in case this happens again, so folks could at least side-load it. 🤔
