### ISSUE TITLE
Wrong Frequency at DTMF

### ISSUE THREAD

**Issue by Frischid** [Fortyseven/ToneDef#17]
After making a FFT I saw that the frequencies are not as they should be for DTMF ( compared to Wikipedia )

Would be necessary to fix this, thanks !

**Comment by Fortyseven** [comment]
Interesting. I'm no longer directly supporting this project, but I feel confident in saying that it's been tested and used over the years by numerous people with a variety of DTMF decoders. This is the first time someone has suggested there was an issue like this. 

So let me toss out some possible avenues to explore before we look any deeper:

- [ ]  The FFT analysis is flawed or misinterpreted. Don't take offense -- in light of what I just said about it being tested successfully for a long time, it's worth at least considering.

- [ ]  Perhaps you're right, and most MF decoders have a decent frequency tolerance that ToneDef has been working within, and it could be tightened up somehow. 

- [ ]  The device producing the tones might be playing them back off a bit. (?) Worth testing against various devices. Or look for an EQ setting that might be enabled.

- [ ]   It could be that an update to Android has subtly changed how sound is produced. (Unlikely, but worth noting as a possibility.)

Otherwise, more specific details of your test results versus expectations would be appreciated. If we can build a repeatable, solid case for this, I would be willing to entertain pulling the project out of mothballs and looking into a fix. 💪

**Comment by tildearrow** [comment]
See pull request #13. It should fix the issue.

**Comment by tildearrow** [comment]
Repeatable solid case:
- Open the DTMF tone pad
- Hold a button for around ~30 seconds
- At some point the frequency will deviate

The actual reason for wrong frequency is, surprisingly, a floating point rounding error. When a tone is generated, the counter (a floating point number which is sin()'d to generate the sine tone) does not overflow at pi, but rather continues its increment indefinitely. At some point, the value is too high that the counter loses precision and begins to increment at a slightly slower/faster pace, which causes the frequency to deviate.

**Comment by Fortyseven** [comment]
Should be fixed in build 17, tonight or tomorrow.
